# Generated by Django 6.0.5 on 2026-05-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notebook_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebookcell",
            name="type",
            field=models.CharField(
                choices=[("python", "Python"), ("markdown", "Markdown")],
                default="python",
                max_length=10,
            ),
        ),
    ]
